apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gocdb.fullname" . }}
  labels:
    {{- include "gocdb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gocdb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gocdb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          env:
          - name: GOCDB_DATABASE_SERVER
            value: gocdb-database
