dependencies:
- name: revad
  version: "1.0.0"
  repository: "https://cs3org.github.io/charts"
  alias: gateway
- name: revad
  version: "1.0.0"
  repository: "https://cs3org.github.io/charts"
  alias: storageprovider-home
  condition: storageProviders.home.enabled
- name: revad
  version: "1.0.0"
  repository: "https://cs3org.github.io/charts"
  alias: storageprovider-reva
  condition: storageProviders.reva.enabled
- name: wopiserver
  version: "0.1.0"
  repository: "https://cs3org.github.io/charts"
  condition: wopiserver.enabled
