ingress:
  enabled: false
  hostname: iop.local
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  tls: []
    # Secrets must be present in the namespace beforehand.
    # - secretName: iop-tls
    #   hosts:
    #     - iop.local
