ingress:
  enabled: false
  hostname: iop.local
  path: /
  servicePort: http
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #
    # To expose the REVA grpc service pass servicePort: grpc
    # as value with this annotation:
    # nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  tls: []
    # Secrets must be present in the namespace beforehand.
    # - secretName: iop-tls
    #   hosts:
    #     - iop.local
