dependencies:
- name: prometheus
  version: 11.2.2
  repository: "https://kubernetes-charts.storage.googleapis.com"
- name: grafana
  version: 5.0.24
  repository: "https://kubernetes-charts.storage.googleapis.com"
