prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      enabled: false

grafana:
  adminUser: admin
  adminPassword: admin
  # sidecar:
  #   dashboards:
  #     enabled: true
  #     label: grafana_dashboard
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://centralbrain-prometheus-server
          access: proxy
          isDefault: true
